#!/bin/sh -e

destdir="${1:-.}"

version=$(git describe --tags --always --dirty)
name=qarv-$version
sed -i "s/@@VERSION@@/$version/" CMakeLists.txt
echo "CMakeLists.txt has beed dirtied, don't forget to undo." 1>&2
git archive --prefix=$name/ HEAD | \
  xz -9 > $destdir/$name.tar.xz
